import {validateModel,scoreText} from './trained-classifier.mjs';
import {loadDocument} from '../shared/browser/files.mjs';
const $=s=>document.querySelector(s),status=$('#classifier-status'),results=$('#classifier-results');
const names={pay_statement:'Pay statement',invoice_or_receipt:'Invoice or receipt',other_document:'Other document',unknown:'Unknown — needs review'};
let model=null,epoch=0;
function note(message){status.textContent=message;}
function element(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function display(name,result){const card=element('article','');card.className='card pad';card.dataset.classifierResult=result.label;card.append(element('h2',name),element('h3',names[result.label]));card.append(element('p',result.reason==='model_suggestion'?'Experimental suggestion. Check the source before using this type.':result.reason==='insufficient_text'?'Not enough readable text to classify.':result.reason==='text_too_long'?'This text exceeds the model’s processing limit.':'The score is below the selected threshold. Leave the type unknown.'));if(result.scores.length){const table=element('table','');table.append(element('caption','Model scores — not accuracy probabilities'));model.labels.forEach((label,i)=>{const row=element('tr','');row.append(element('th',names[label]),element('td',result.scores[i].toFixed(3)));table.append(row);});card.append(table);}results.append(card);}
$('#classify').disabled=true;
try{model=validateModel(await(await fetch(new URL('../models/public-type-model.json',import.meta.url))).json());$('#classify').disabled=false;note('Trained model ready. Inference runs locally in this page.');}catch{note('The packaged classifier could not load. Rebuild the extension.');}
$('#classify').addEventListener('click',()=>{if(!model)return;display('Pasted document text',scoreText(model,$('#classifier-text').value));note('Classification complete. No facts were extracted or confirmed.');});
$('#clear-classifier').addEventListener('click',()=>{epoch++;$('#classifier-text').value='';$('#classifier-files').value='';results.replaceChildren();note('This classifier page is clear.');});
$('#classifier-files').addEventListener('change',async event=>{const files=[...event.target.files];event.target.value='';if(!model)return note('Wait for the model to load.');const token=++epoch;if(files.length>24)return note('Select at most 24 documents.');let bytes=0;for(const file of files){if(token!==epoch)return;bytes+=file.size;if(bytes>48_000_000){note('Batch exceeds 48 MB.');return;}note('Reading '+file.name);try{const doc=await loadDocument(file,{allowText:true});if(token!==epoch)return;if(doc.pages.some(p=>!p.text.trim()))display(doc.filename,{label:'unknown',scores:[],reason:'insufficient_text'});else display(doc.filename,scoreText(model,doc.pages.map(p=>p.text).join('\n')));}catch{if(token!==epoch)return;const card=element('article','');card.className='card pad';card.append(element('h2',file.name),element('p','Could not read this file. Use a readable PDF or UTF-8 text within the import limits.'));results.append(card);}}if(token===epoch)note('Batch finished. Experimental suggestions only.');});
window.addEventListener('pagehide',()=>{epoch++;model=null;});
