import {zipStore} from '../shared/core/zip.mjs';
import {FORMS,emptyAnswers,reviseAnswer,reviseGroup,confirmApplication,currentApplication,compatibleFacts,adoptFact,prefillApplication} from './form-adapter.mjs';
import {formPlan,releasedMap} from './form-renderer.mjs';
import {loadFormAssets,renderInWorker,previewPdf} from './form-browser.mjs';
let active=null,job=null,output=null,serial=0;
const formAssets=new Map();
export function clearFormPreview(){serial++;job?.abort();job=null;output=null;active=null;}
export const applicationFormButtons=(program)=>`<button class="btn btn-secondary" data-action="official-form" data-form="${program==='CalFresh'?'cf285':'ccfrm604'}">Generate ${program} package (${program==='CalFresh'?'CF285':'CCFRM604'})</button>`;
export function applicationAnswerSummary(state,id,esc){
 const d=state.formAnswers[id],assets=formAssets.get(id),answered=d?.answers.filter(a=>a.status==='answered')||[];
 if(!answered.length)return '<section class="application-answer-summary"><h3>Your application answers</h3><p>No application answers entered yet. Prepare your answers below. Quick-check estimates are not copied into exact PDF fields.</p></section>';
 const current=currentApplication(d,state);
 return `<section class="application-answer-summary"><h3>Your application answers</h3><p>${current?'Confirmed for preparation':'Draft — review and confirm these answers'}. These are the values selected for your application draft.</p><dl class="cf-facts">${answered.map(a=>{
 const group=d.groups.find(g=>g.groupId===a.groupId),definition=assets?.inventory.groups.find(g=>g.id===a.groupId),label=definition?.fields.find(f=>f.key===a.field)?.label||a.field.replaceAll('_',' '),bindings=assets?.map.bindings.filter(b=>b.groupId===a.groupId&&b.row===a.row&&b.field===a.field&&(b.optionValue===undefined||b.optionValue===a.value))||[];
 const excluded=group?.status!=='applicable'||a.row>=group.rowCount;
 const pages=[...new Set(bindings.map(b=>b.page))];
 const destination=excluded?'Not included — section deferred, not applicable, or record removed':group.rowCount>definition?.printedCapacity?'Manual continuation required':pages.length?`PDF page${pages.length>1?'s':''} ${pages.join(', ')} · unsigned draft`:'Complete manually on the official form';
 return `<div><dt>${esc(label)}<small>${esc(definition?.label||a.groupId)} · Record ${a.row+1}</small></dt><dd>${esc(typeof a.value==='boolean'?(a.value?'Yes':'No'):a.value)}<small>${esc(destination)}</small></dd></div>`;
 }).join('')}</dl></section>`;
}
export function connectForms({getState,modal,esc,btn,download,close,refresh=()=>{}}){
 const state=()=>getState(),data=()=>state().formAnswers[active.id];
 const key=a=>`${a.groupId}|${a.row}|${a.field}`;
 function editor(){const expanded=[...document.querySelectorAll('.form-group[open]')].map(el=>el.dataset.groupView);const {inventory,map,id}=active,d=data();
  modal(`${FORMS[id]} application details`,`<p>Prepare an unsigned copy of ${esc(inventory.title)}. Answer the sections that apply, or leave them for the original form. Available reviewed details are filled in below. Check them and add only what is missing. Income ranges are not treated as exact amounts.</p><p>Generate an unsigned draft using the original official form. Check the filled pages and complete missing items before signing or submitting.</p>${d.demoFixture?'<p><strong>Fictional demo — do not submit.</strong> These additional answers come from the demo questionnaire. They are not AI-extracted facts.</p>':''}<div id="form-editor">${inventory.groups.filter(g=>!g.manualOnly&&map.bindings.some(b=>b.groupId===g.id)).map(g=>{
   const group=d.groups.find(x=>x.groupId===g.id),status=group?.status||'deferred',rows=group?.rowCount||1;
   return `<details class="form-group" data-group-view="${g.id}"${expanded.includes(g.id)||(!expanded.length&&g===inventory.groups.find(x=>!x.manualOnly&&map.bindings.some(b=>b.groupId===x.id)))?' open':''}><summary>${esc(g.label)}</summary><label>Prepare this section<select data-form-group="${g.id}">${[['deferred','Answer on the official form'],['applicable','Yes — prepare answers here'],['not_applicable','Not applicable']].map(([v,t])=>`<option value="${v}"${status===v?' selected':''}>${t}</option>`).join('')}</select></label>${status!=='not_applicable'?`${status==='deferred'?'<p>Enter an answer to include this section. Leave it blank to finish on the official form.</p>':''}${g.printedCapacity>1?`<label>Number of people or records<input type="number" min="1" max="100" value="${rows}" data-form-rows="${g.id}"></label>`:''}${rows>g.printedCapacity?`<p>Only ${g.printedCapacity} records fit here. This section will need manual continuation; no records will be silently dropped.</p>`:''}${Array.from({length:Math.min(rows,g.printedCapacity)},(_,row)=>`<fieldset><legend>Record ${row+1}</legend>${g.fields.filter(f=>map.bindings.some(b=>b.groupId===g.id&&b.row===row&&b.field===f.key)).map(f=>{
    const k=key({groupId:g.id,row,field:f.key}),a=d.answers.find(x=>key(x)===k),bs=map.bindings.filter(b=>b.groupId===g.id&&b.row===row&&b.field===f.key),choices=[...new Set(bs.filter(b=>b.optionValue!==undefined).map(b=>b.optionValue))],sources=compatibleFacts(state(),f.key);
    const control=choices.length?`<select data-form-answer="${k}" data-answer-type="${f.type}"><option value="">Leave unanswered</option>${choices.map(v=>`<option value="${esc(String(v))}"${a?.status==='answered'&&a.value===v?' selected':''}>${typeof v==='boolean'?v?'Yes':'No':esc(v)}</option>`).join('')}</select>`:`<input data-form-answer="${k}" value="${esc(a?.status==='answered'?a.value:'')}" maxlength="4000">`;
    return `<label class="field">${esc(f.label)}${control}</label>${a?.autoPrefilled&&a.status==='answered'?'<small>Filled from your reviewed details. You can edit this value.</small>':''}${sources.length?`<label>Use a confirmed source for this answer<select data-form-source="${k}"><option value="" disabled${a?.sourceRefs?.length===1&&sources.some(f=>f.id===a.sourceRefs[0].id)?'':' selected'}>Choose a source (optional)</option>${sources.map(f=>{const doc=state().docs.find(d=>d.id===f.documentId),chosen=a?.sourceRefs?.length===1&&a.sourceRefs[0].id===f.id;return `<option value="${esc(f.id)}"${chosen?' selected':''}>${esc([f.value,doc?.filename||'Entered detail',f.page?'Page '+f.page:'',f.period].filter(Boolean).join(' · '))}</option>`;}).join('')}</select></label>`:''}`;}).join('')}</fieldset>`).join('')}`:''}</details>`;}).join('')}</div><p>Signatures, consent/elections, sensitive identity details, and other unsupported questions must be completed directly on the original form. Confirmation here is not a signature.</p><a href="${inventory.officialUrl}" target="_blank" rel="noopener noreferrer">Open official blank application</a>`,btn('form-confirm','Confirm these application answers',true)+btn('close','Done'));
 }
 function planView(){const d=data(),{inventory,map}=active,plan=formPlan(inventory,map,d);active.plan=plan;
  modal(`${FORMS[active.id]} application answers`,`${applicationAnswerSummary(state(),active.id,esc)}<p>${plan.operations.length?`${plan.operations.length} PDF field placements planned.`:'No PDF field placements planned yet. Enter application answers to prepare them.'} ${plan.missing.length} entries or sections still need attention. Nothing is signed or submitted.</p>${!releasedMap(map)?'<p role="status">The field mapping has not completed independent review. Your download will be marked as an unsigned draft. Review every filled value and finish any missing items on the official form.</p>':''}<details><summary>Items to finish on the form</summary><ul>${plan.missing.map(m=>`<li>${esc(inventory.groups.find(g=>g.id===m.groupId)?.label||m.groupId)}${m.field?' · '+esc(m.field.replaceAll('_',' ')):''}: ${esc(m.reason.replaceAll('_',' '))}</li>`).join('')}${plan.manualActions.map(m=>`<li>Page ${m.page}: ${esc(m.text)}</li>`).join('')}</ul></details><a href="${inventory.officialUrl}" target="_blank" rel="noopener noreferrer">Open official application</a>`,btn('form-preview','Generate filled application draft',true)+btn('form-blank','Preview blank official form')+btn('form-edit','Edit application answers')+btn('close','Done'));
 }
 async function action(a,b){
  if(a==='official-form'){clearFormPreview();const id=b.dataset.form;const token=serial;const assets=await loadFormAssets(id);if(token!==serial)return true;active={id,...assets};formAssets.set(id,assets);state().formAnswers[id]??=emptyAnswers(id);prefillApplication(data(),state(),assets.map);refresh();if(currentApplication(data(),state()))planView();else editor();return true;}
  if(!a.startsWith('form-'))return false;if(!active)throw Error('Reopen application details.');
  if(a==='form-edit'){job?.abort();output=null;editor();return true;}
  if(a==='form-review'){job?.abort();output=null;planView();return true;}
  if(a==='form-blank'){
   const token=++serial;job?.abort();job=new AbortController();const signal=job.signal;
   modal('Blank official application',`<p>This is the original blank form. Your entered answers have not been added.</p><p id="blank-preview-status" role="status">Loading pages…</p><div id="official-preview"></div>`,btn('form-review','Back to my answers',true)+btn('close','Done'));
   try{await previewPdf(active.template,document.querySelector('#official-preview'),signal);if(!signal.aborted&&token===serial)document.querySelector('#blank-preview-status').textContent='All pages loaded. This form is blank.';}catch(e){if(signal.aborted||token!==serial)return true;document.querySelector('#blank-preview-status').textContent='Preview could not load. Your answers are still available. Go back to open the official form or try again.';}return true;
  }
  if(a==='form-confirm'){for(const el of document.querySelectorAll('[data-form-answer]')){const [groupId,row,field]=el.dataset.formAnswer.split('|');const old=data().answers.find(a=>a.groupId===groupId&&a.row===Number(row)&&a.field===field);const displayed=old?.status==='answered'?String(old.value):'';if(el.value!==displayed)input({target:el});}state().formAnswers[active.id]=confirmApplication(data(),state());refresh();planView();return true;}
  if(a==='form-preview'){
   if(!currentApplication(data(),state()))throw Error('Answers changed. Review and confirm the current answers first.');
   if(!formPlan(active.inventory,active.map,data()).operations.length)throw Error('No answers are ready to fill. Choose Edit application answers, enter the details you know, then confirm them. You can also preview the blank form.');
   const snapshot=structuredClone(data()),token=++serial;job?.abort();job=new AbortController();const signal=job.signal;
   modal('Preparing your application','<p>Filling the original form on your device…</p>',btn('close','Cancel'));
   try{
   const result=await renderInWorker({...active,answers:snapshot,mode:releasedMap(active.map)?'released':'draft'},signal);
   if(signal.aborted||token!==serial)return true;
   if(!currentApplication(snapshot,state())||data().revision!==snapshot.revision)throw Error('Answers changed. Generate a new preview.');
   output={...result,snapshot};modal('Review your unsigned application',`<p>${result.report.status==='partial_unsigned_draft'?'Partially filled application — items still need attention.':'Filled application ready for your review and signature.'}</p>${result.report.fictionalDemo?'<p><strong>Fictional demo — do not submit.</strong></p>':''}<p>${result.report.written.length} fields filled; ${result.report.missing.length} unresolved items. Inspect each page and finish all required signatures and consent choices yourself.</p>${result.report.mode==='draft'?'<p>Unsigned draft — independent mapping review is incomplete. Nothing has been submitted.</p>':''}<details><summary>Items to finish</summary><ul>${result.report.missing.map(m=>`<li>${esc(m.groupId)}${m.field?' · '+esc(m.field):''}: ${esc(m.reason.replaceAll('_',' '))}${m.value!==undefined?' · Your value: '+esc(m.value):''}</li>`).join('')}${result.report.manualActions.map(m=>`<li>Page ${m.page}: ${esc(m.text)}</li>`).join('')}</ul></details><div id="official-preview"></div>`,btn('form-save','Download filled PDF',true,'disabled')+btn('form-package','Download application package',false,'disabled')+btn('form-review','Back to answers')+btn('close','Done'));
   await previewPdf(result.bytes,document.querySelector('#official-preview'),signal);if(!signal.aborted&&token===serial&&currentApplication(snapshot,state())){document.querySelector('[data-action=form-save]').disabled=false;document.querySelector('[data-action=form-package]').disabled=false;}return true;
   }catch(error){if(signal.aborted||token!==serial)return true;output=null;planView();document.querySelector('#dialog-error').textContent=error.message||'Application could not be generated. Your answers are still available. Try again.';return true;}
  }
  if(a==='form-save'||a==='form-package'){if(!output||!currentApplication(output.snapshot,state())||data().revision!==output.snapshot.revision)throw Error('This preview is stale. Generate it again.');if(a==='form-save')download(output.bytes,`${active.id}-unsigned.pdf`,'application/pdf');else{
    const checklist=[output.report.fictionalDemo?'FICTIONAL DEMO — DO NOT SUBMIT':'UNSIGNED APPLICATION DRAFT — REVIEW BEFORE USE',FORMS[active.id]+' · '+active.inventory.title,'Nothing has been signed or submitted.',output.report.independentlyValidated?'':'Independent mapping review is incomplete. Check every populated field.',...output.report.missing.map(m=>`${m.groupId}${m.field?' / '+m.field:''}: ${m.reason.replaceAll('_',' ')}${m.value!==undefined?' — Your value: '+m.value:''}`),...output.report.manualActions.map(m=>`Page ${m.page}: ${m.text}`)].filter(Boolean).join('\n');
    download(zipStore([{name:`${active.id}-unsigned.pdf`,data:output.bytes},{name:'items-to-finish.txt',data:checklist},{name:'application-answers.json',data:JSON.stringify(output.snapshot,null,2)},{name:'generation-report.json',data:JSON.stringify(output.report,null,2)}]),`${active.id}-application-package.zip`,'application/zip');
   }return true;}
  return false;
 }
 function input(event){const el=event.target;if(!active)return;
  if(el.dataset.formAnswer){const [groupId,row,field]=el.dataset.formAnswer.split('|');const group=data().groups.find(g=>g.groupId===groupId);if(el.value!==''&&group?.status!=='applicable'){reviseGroup(data(),groupId,'applicable',group?.rowCount||1);const control=document.querySelector(`[data-form-group="${groupId}"]`);if(control)control.value='applicable';}reviseAnswer(data(),{groupId,row:Number(row),field,status:el.value===''?'unknown':'answered',value:el.dataset.answerType==='bool'?el.value==='true':el.value,sourceIds:['owner-entry']});output=null;job?.abort();refresh();}
 }
 function change(event){const el=event.target;if(!active)return;
  if(el.dataset.formGroup){const old=data().groups.find(g=>g.groupId===el.dataset.formGroup);reviseGroup(data(),el.dataset.formGroup,el.value,old?.rowCount||1);refresh();editor();}
  if(el.dataset.formRows){const count=Number(el.value);if(!Number.isInteger(count)||count<1||count>100){el.setCustomValidity('Enter 1–100 records.');el.reportValidity();return;}reviseGroup(data(),el.dataset.formRows,'applicable',count);refresh();editor();}
  if(el.dataset.formSource&&el.value){const [groupId,row,field]=el.dataset.formSource.split('|');adoptFact(data(),state(),{groupId,row:Number(row),field},el.value);const group=data().groups.find(g=>g.groupId===groupId);if(group?.status!=='applicable')reviseGroup(data(),groupId,'applicable',group?.rowCount||1);refresh();editor();}
 }
 return {action,input,change};
}
