import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {demoApplicationAnswers} from '../src/demo-application.mjs';
import {confirmApplication} from '../src/form-adapter.mjs';
import {initial} from '../src/state.mjs';
import {renderOfficialForm} from '../src/form-renderer.mjs';
import {PDFDocument} from '../vendor/pdf-writer/pdf-lib.mjs';
for(const id of ['cf285','ccfrm604'])test(id+' rich demo fills household, address, and income on the original PDF',async()=>{
 const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url));
 const raw=demoApplicationAnswers()[id];assert(!raw.exportAuthorized);assert(raw.answers.every(a=>!a.confirmedRevision));
 const answers=confirmApplication(raw,initial());
 const result=await renderOfficialForm({template:new Uint8Array(read('forms/templates/'+id+'.pdf')),inventory:JSON.parse(read('forms/inventory/'+id+'.json')),map:JSON.parse(read('forms/maps/'+id+'.json')),answers,fontBytes:new Uint8Array(read('vendor/pdf-writer/NotoSans-Regular.ttf')),mode:'draft'});
 assert(result.report.fictionalDemo);assert(!result.report.submitted);assert(!result.report.signatureApplied);assert(result.report.written.length>30);
 assert(result.report.written.some(o=>o.text==='123 Example Lane'));assert(result.report.written.some(o=>o.text==='2550.00'));assert(result.report.written.some(o=>o.text.includes('Riley')));
 const doc=await PDFDocument.load(result.bytes);assert.equal(doc.getPageCount(),id==='cf285'?18:44);
 for(const o of result.report.written.filter(o=>o.kind==='text'))assert.equal(doc.getForm().getTextField(o.widget).getText(),o.text);
 fs.writeFileSync(new URL('../forms/validation/'+id+'-rich-ai-demo.pdf',import.meta.url),result.bytes);
 fs.writeFileSync(new URL('../forms/validation/'+id+'-rich-ai-demo.report.json',import.meta.url),JSON.stringify(result.report,null,2));
});
