import test from 'node:test';import assert from 'node:assert/strict';
import {initial,addDocument,setFact,confirmFacts,usable,recordEvent,transferSnapshot,transferCurrent,deleteAllSourceCopies,historical} from '../src/state.mjs';
import {runDoctor,reconcileDoctor,explainFinding,linkRequest} from '../src/doctor.mjs';
import {extractByLabels} from '../shared/core/labels.mjs';
import {validateExtraction} from '../shared/core/schema.mjs';
const doc=(s,kind,values,id='a')=>{addDocument(s,{id,hash:id,filename:id+'.pdf',pages:[{page:1,text:'test'}],bytes:new Uint8Array([1])},{kind,analysisState:'complete',fields:Object.entries(values).map(([key,value])=>({key,value,sourceValue:value,page:1,quote:key+': '+value}))});};
const fact=(s,key,id='a')=>s.facts.find(f=>f.documentId===id&&f.fieldKey===key);
const rule=(s,id)=>runDoctor(s).trace.filter(f=>f.ruleId===id);
for(const [name,current,previous,total,proposed,status] of [
 ['previous balance used','140.00','800.00','940.00','940.00','finding'],
 ['large current charge','940.00','0.00','940.00','940.00','clear'],
 ['correct basis','140.00','800.00','940.00','140.00','clear'],
 ['unreconciled credit','140.00','800.00','900.00','900.00','needs_context'],
 ['unknown previous balance','140.00',null,'940.00','940.00','needs_context']])test('bill: '+name,()=>{
 const s=initial();doc(s,'utility',{current_charges:current,...(previous===null?{}:{prior_balance:previous}),amount_due:total});setFact(s,fact(s,'current_charges'),proposed);assert.equal(rule(s,'PD08')[0].state,status);assert.equal(rule(s,'PD08')[0].officialApplicationRouteVisible,true);
 if(status==='finding'){confirmFacts(s);assert.equal(usable(fact(s,'current_charges')),false);assert.equal(usable(fact(s,'amount_due')),true);}
});
test('correction resolves issue without changing source or old snapshot',()=>{const s=initial();doc(s,'utility',{current_charges:'140.00',prior_balance:'800.00',amount_due:'940.00'});confirmFacts(s);const old=s.snapshots[0];setFact(s,fact(s,'current_charges'),'940');reconcileDoctor(s);assert.equal(usable(fact(s,'current_charges')),false);setFact(s,fact(s,'current_charges'),'140');confirmFacts(s);assert.equal(rule(s,'PD08')[0].state,'clear');assert.equal(old.facts.find(f=>f.fieldKey==='current_charges').value,'140.00');assert.equal(s.docs[0].fields[0].value,'140.00');});
test('explanation is revision-bound and does not confirm facts',()=>{const s=initial();doc(s,'utility',{current_charges:'140.00',prior_balance:'800.00',amount_due:'940.00'});setFact(s,fact(s,'current_charges'),'940');const finding=rule(s,'PD08')[0];assert.throws(()=>explainFinding(s,finding.id,''));explainFinding(s,finding.id,'I checked the source; the extracted current label was incorrect.');assert.equal(usable(fact(s,'current_charges')),false);confirmFacts(s);assert.equal(usable(fact(s,'current_charges')),true);setFact(s,fact(s,'current_charges'),'140');setFact(s,fact(s,'current_charges'),'940');assert.equal(rule(s,'PD08')[0].resolution,undefined);});
for(const [value,expected] of [['1000.00',true],['15000.00',true],['1250.00',false],['1400.00',false]])test('gross basis '+value,()=>{const s=initial();doc(s,'paystub',{gross_pay:'1250.00',net_pay:'1000.00',ytd_gross:'15000.00'});setFact(s,fact(s,'gross_pay'),value);assert.equal(rule(s,'PD04').length>0,expected);});
const pay={person:'Alex Demo',issuer:'Fictional Work',period_start:'2026-09-01',period_end:'2026-09-15',pay_date:'2026-09-18',gross_pay:'1250.00'};
for(const [name,change,expected] of [['conflict',{gross_pay:'1300.00'},true],['equal',{},false],['other person',{person:'Sam Demo',gross_pay:'1300.00'},false],['other period',{period_start:'2026-10-01',period_end:'2026-10-15',gross_pay:'1300.00'},false],['other payment',{pay_date:'2026-09-20',gross_pay:'1300.00'},false]])test('pay comparison '+name,()=>{const s=initial();doc(s,'paystub',pay);doc(s,'paystub',{...pay,...change},'b');assert.equal(rule(s,'PD07').length>0,expected);});
function requestCase({start='2026-09-01',end='2026-09-15',person='Alex Demo',program='CalFresh',basis='earned',confirm=true}={}){const s=initial();doc(s,'paystub',pay);doc(s,'county_request',{},'request');if(confirm)confirmFacts(s);const e=recordEvent(s,{kind:'evidence_request',sourceId:'request',details:'Provide income record',person,program,periodStart:start,periodEnd:end,periodBasis:basis});linkRequest(s,{requestId:e.id,documentId:'a',program:'CalFresh',recordBasis:'earned'});return s;}
for(const [name,opts,result] of [['historical match',{},'clear'],['different month',{start:'2026-10-01',end:'2026-10-31'},'finding'],['partial month',{end:'2026-09-30'},'finding'],['missing confirmation',{confirm:false},'needs_context'],['ambiguous date meaning',{basis:''},'needs_context'],['other person',{person:'Another Person'},'finding'],['other program',{program:'Medi-Cal'},'finding']])test('request '+name,()=>{const s=requestCase(opts),trace=runDoctor(s).trace.filter(f=>['PD05','PD06'].includes(f.ruleId));assert.equal(trace[0].state,result);assert.equal(trace[0].officialApplicationRouteVisible,true);});
test('history is not automatically expired by import date',()=>{const s=requestCase();historical(s,'a');assert.equal(rule(s,'PD05')[0].state,'needs_context');historical(s,'a');confirmFacts(s);assert.equal(rule(s,'PD05')[0].state,'clear');});
test('new event invalidates prepared transfer; receipt cannot become submission',()=>{const s=requestCase(),snapshot=transferSnapshot(s);recordEvent(s,{kind:'upload_receipt',sourceId:'request',program:'CalFresh',details:'Upload recorded',requestId:s.events[0].id});assert.equal(transferCurrent(s,snapshot),false);assert.equal(rule(s,'PD12').length,0);});
test('delete all copies removes history and dependent events',()=>{const s=requestCase();deleteAllSourceCopies(s,'a');assert.ok(!s.facts.some(f=>f.documentId==='a'));assert.equal(s.snapshots.length,0);assert.equal(s.events.length,0);assert.equal(s.requestMatches.length,0);});
test('stale confirmation is rejected',()=>{const s=initial();doc(s,'utility',{current_charges:'140.00'});const rev=s.revision;setFact(s,fact(s,'current_charges'),'150');assert.throws(()=>confirmFacts(s,rev));assert.equal(s.snapshots.length,0);});
for(const [title,kind,label]of [['Application submission receipt','application_receipt','Program'],['Document upload receipt','upload_receipt','Program'],['County evidence request','county_request','Requested evidence'],['Business income statement','self_employment','Gross business receipts'],['Income award','income_award','Award amount']])test('local recognition: '+title,()=>{const pages=[{page:1,text:title+'\n'+label+': '+(kind==='self_employment'||kind==='income_award'?'100.00':'CalFresh')}];assert.equal(extractByLabels(pages).kind,kind);});
test('mixed documents abstain, unsupported model fields and invented quotes rejected',()=>{assert.equal(extractByLabels([{page:1,text:'Pay statement\nUtility statement'}]).kind,'unknown');assert.throws(()=>validateExtraction({kind:'unknown',fields:[],warnings:[],approved:true},[]));assert.equal(validateExtraction({kind:'utility',fields:[{key:'current_charges',value:'140.00',page:1,quote:'Invented'}],warnings:[]},[{page:1,text:'Current charges: 150.00'}]).fields.length,0);});
test('integer cents are stored and updated exactly',()=>{const s=initial();doc(s,'utility',{current_charges:'140.01'});assert.equal(fact(s,'current_charges').cents,14001);setFact(s,fact(s,'current_charges'),'0.10');assert.equal(fact(s,'current_charges').cents,10);});
test('known upload receipt cannot be recorded as an application receipt',()=>{const s=initial();doc(s,'upload_receipt',{},'upload');assert.throws(()=>recordEvent(s,{kind:'application_receipt',program:'CalFresh',sourceId:'upload',details:'Wrong type'}),/different/);assert.equal(s.events.length,0);});
