import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initial} from '../src/state.mjs';
import {emptyAnswers,prefillApplication,reviseAnswer,confirmApplication,currentApplication} from '../src/form-adapter.mjs';
const map=id=>JSON.parse(fs.readFileSync(new URL(`../forms/maps/${id}.json`,import.meta.url)));
function evidence(){const s=initial();s.docs=[{id:'pay1',kind:'paystub'}];s.facts=['person','issuer','gross_pay','pay_frequency'].map((fieldKey,i)=>({id:'f'+i,documentId:'pay1',fieldKey,value:['Jordan Rivera','Example Company','1250.00','biweekly'][i],person:'Jordan Rivera',period:'2026-09-01 — 2026-09-14',page:1,revision:1,confirmedRevision:1}));return s;}
const answer=(a,g,f)=>a.answers.find(x=>x.groupId===g&&x.field===f);
test('reviewed name and employer prefill CF285 without converting pay into a monthly total',()=>{const s=evidence(),a=emptyAnswers('cf285');assert(prefillApplication(a,s,map('cf285'))>0);assert.equal(answer(a,'q1.contact','name').value,'Jordan Rivera');assert.equal(answer(a,'q8.earned','employer_name_address').value,'Example Company');assert.equal(answer(a,'q8.earned','frequency').value,'biweekly');assert(!answer(a,'q8.earned','gross_received_this_month'));assert(!answer(a,'q1.contact','home_address'));assert(answer(a,'q1.contact','name').sourceRefs.length);assert.equal(prefillApplication(a,s,map('cf285')),0);});
test('Medi-Cal keeps a reviewed payment paired with its frequency',()=>{const s=evidence(),a=emptyAnswers('ccfrm604');prefillApplication(a,s,map('ccfrm604'));assert.equal(answer(a,'p7.income','amount').value,'1250.00');assert.equal(answer(a,'p7.income','frequency').value,'Every 2 weeks');assert(!answer(a,'p1.contact','first_name'));assert.equal(answer(a,'p7.income','amount').sourceRefs.length,2);});
test('conflicting people are not silently assigned as applicant; unreviewed evidence is excluded',()=>{const s=evidence();s.facts.push({...s.facts[0],id:'other',value:'Sam Rivera',person:'Sam Rivera'});const a=emptyAnswers('cf285');prefillApplication(a,s,map('cf285'));assert(!answer(a,'q1.contact','name'));s.facts.forEach(f=>f.confirmedRevision=null);const b=emptyAnswers('cf285');prefillApplication(b,s,map('cf285'));assert.equal(b.answers.length,0);});
test('manual correction survives automatic refresh; stale source clears imported answers',()=>{const s=evidence(),a=emptyAnswers('cf285');prefillApplication(a,s,map('cf285'));reviseAnswer(a,{groupId:'q1.contact',row:0,field:'name',status:'answered',value:'My correction'});s.facts[1].revision++;s.facts[1].confirmedRevision=null;prefillApplication(a,s,map('cf285'));assert.equal(answer(a,'q1.contact','name').value,'My correction');assert.equal(answer(a,'q8.earned','employer_name_address').status,'unknown');});
test('two pay statements for one employer stay one row, differing payments require review',()=>{const s=evidence();s.docs.push({id:'pay2',kind:'paystub'});s.facts.push(...s.facts.map(f=>({...f,id:f.id+'2',documentId:'pay2',value:f.fieldKey==='gross_pay'?'1300.00':f.value})));const a=emptyAnswers('ccfrm604');prefillApplication(a,s,map('ccfrm604'));assert.equal(a.groups.find(g=>g.groupId==='p7.income').rowCount,1);assert(!answer(a,'p7.income','amount'));});
test('confirming prefilled answers preserves source revisions for PDF invalidation',()=>{const s=evidence(),a=emptyAnswers('cf285');prefillApplication(a,s,map('cf285'));const c=confirmApplication(a,s);assert(currentApplication(c,s));s.facts[0].revision++;assert(!currentApplication(c,s));});
