import test from 'node:test';
import assert from 'node:assert/strict';
import {parseMoney,validPeriod,comparePeriods,checkPriorBalance,checkRecordedCashflow,matchRecordToRequest,policyMayRun,selectConfirmedFacts,recordSubmission,acceptJobResult} from '../reference/kernel.mjs';
for(const [v,n] of [['0',0],['12',1200],['12.5',1250],['12.50',1250],['-12.50',-1250],['-0',0],['9999999999.99',999999999999]])test(`money ${v}`,()=>assert.equal(parseMoney(v),n));
for(const v of ['',null,'1,200','$1200','1e3','NaN','01.00','2.001','10000000000'])test(`reject ambiguous money ${v}`,()=>assert.throws(()=>parseMoney(v)));
const oct={start:'2026-10-01',end:'2026-10-31'},sept={start:'2026-09-01',end:'2026-09-30'};
test('valid calendar leap day',()=>assert.equal(validPeriod({start:'2024-02-29',end:'2024-02-29'}),true));
test('invalid leap day',()=>assert.equal(validPeriod({start:'2026-02-29',end:'2026-03-01'}),false));
test('reversed dates',()=>assert.equal(validPeriod({start:'2026-10-31',end:'2026-10-01'}),false));
test('missing date unknown',()=>assert.equal(comparePeriods({},oct),'unknown'));
test('full period coverage',()=>assert.equal(comparePeriods(oct,oct),'covers'));
test('separate periods',()=>assert.equal(comparePeriods(sept,oct),'disjoint'));
test('partial coverage',()=>assert.equal(comparePeriods({start:'2026-10-01',end:'2026-10-15'},oct),'partial'));
const bill={confirmed:true,sameDocument:true,currency:'USD',current:14000,previous:80000,total:94000,proposedCurrent:94000};
test('prior balance catches wrong answer',()=>assert.equal(checkPriorBalance(bill).ruleId,'PD08'));
test('correct answer no warning',()=>assert.equal(checkPriorBalance({...bill,proposedCurrent:14000}).state,'clear'));
test('genuinely high charge not suspicious',()=>assert.equal(checkPriorBalance({...bill,current:94000,previous:0}).state,'clear'));
test('other credits require context',()=>assert.equal(checkPriorBalance({...bill,total:93000,proposedCurrent:93000}).state,'unknown'));
for(const patch of [{confirmed:false},{sameDocument:false},{currency:'EUR'},{current:null}])test(`bill unknown ${JSON.stringify(patch)}`,()=>assert.equal(checkPriorBalance({...bill,...patch}).state,'unknown'));
const cash={confirmed:true,comparable:true,currency:'USD',period:oct,householdId:'h1',income:180000,expenses:260000};
test('cashflow gap is explanation not denial',()=>{const r=checkRecordedCashflow(cash);assert.equal(r.difference,80000);assert.equal(r.eligibilityConclusion,null);assert.deepEqual(r.blocksFactIds,[]);assert.equal(r.officialApplicationRouteVisible,true);});
test('equal totals clear',()=>assert.equal(checkRecordedCashflow({...cash,expenses:180000}).state,'clear'));
test('income above expenses clear',()=>assert.equal(checkRecordedCashflow({...cash,expenses:1000}).state,'clear'));
for(const patch of [{confirmed:false},{comparable:false},{householdId:null},{period:sept,expenses:null},{income:-1}])test(`cashflow unknown ${JSON.stringify(patch)}`,()=>assert.equal(checkRecordedCashflow({...cash,...patch}).state,'unknown'));
const req={ownerConfirmed:true,applicationId:'a1',program:'calfresh',personId:'p1',period:oct,periodBasis:'received'};
const rec={applicationId:'a1',program:'calfresh',personId:'p1',period:sept,periodBasis:'received'};
test('wrong period warning',()=>assert.equal(matchRecordToRequest(rec,req).ruleId,'PD05'));
test('old document relevant to old request',()=>assert.equal(matchRecordToRequest(rec,{...req,period:sept}).state,'period_match'));
test('partial request coverage',()=>assert.equal(matchRecordToRequest({...rec,period:{start:'2026-10-01',end:'2026-10-15'}},req).periodRelation,'partial'));
for(const k of ['applicationId','program','personId'])test(`wrong scope ${k}`,()=>assert.equal(matchRecordToRequest({...rec,[k]:'other'},req).state,'out_of_scope'));
for(const patch of [{ownerConfirmed:false},{personId:null},{periodBasis:'earned'},{period:null}])test(`request unknown ${JSON.stringify(patch)}`,()=>assert.equal(matchRecordToRequest(rec,{...req,...patch}).state,'unknown'));
const pol={status:'approved',enabled:true,sourceIds:['P04'],reviewerIds:['domain','engineering'],programs:['calfresh'],stages:['preparation'],jurisdiction:'CA:SCC',effectiveFrom:'2026-10-01',effectiveTo:'2027-09-30',reviewExpiresAt:'2026-11-01'};
const ctx={onDate:'2026-10-03',program:'calfresh',stage:'preparation',jurisdiction:'CA:SCC'};
test('fully scoped reviewed policy passes reference gate',()=>assert.equal(policyMayRun(pol,ctx),true));
for(const patch of [{status:'research'},{enabled:false},{sourceIds:[]},{reviewerIds:['same','same']},{effectiveFrom:null},{effectiveTo:'2026-10-01'},{reviewExpiresAt:'2026-10-02'}])test(`policy withheld ${JSON.stringify(patch)}`,()=>assert.equal(policyMayRun({...pol,...patch},ctx),false));
for(const patch of [{program:'medi_cal'},{jurisdiction:'CA:LA'},{stage:'application'},{onDate:'bad'}])test(`policy scope withheld ${JSON.stringify(patch)}`,()=>assert.equal(policyMayRun(pol,{...ctx,...patch}),false));
const f={id:'f1',applicationId:'a1',active:true,state:'known',revision:2,confirmedRevision:2,value:14000};const snap={applicationId:'a1',factRevisions:{f1:2}};
test('confirmed copy succeeds',()=>assert.equal(selectConfirmedFacts([f],snap,['f1'],'a1')[0].value,14000));
test('copied fact is detached',()=>{const s=selectConfirmedFacts([f],snap,['f1'],'a1');s[0].value=999;assert.equal(f.value,14000);});
for(const patch of [{revision:3},{confirmedRevision:null},{state:'unknown'},{active:false},{applicationId:'a2'}])test(`copy rejects ${JSON.stringify(patch)}`,()=>assert.throws(()=>selectConfirmedFacts([{...f,...patch}],snap,['f1'],'a1')));
test('duplicate requested fact rejected',()=>assert.throws(()=>selectConfirmedFacts([f],snap,['f1','f1'],'a1')));
test('missing fact rejected',()=>assert.throws(()=>selectConfirmedFacts([],snap,['f1'],'a1')));
const evt={ownerConfirmed:true,applicationId:'a1',programs:['calfresh'],type:'application_receipt',provenance:'imported_owner_confirmed',sourceId:'doc1'};
test('receipt records submission',()=>assert.equal(recordSubmission('not_recorded',evt,'a1','calfresh'),'receipt_recorded'));
for(const patch of [{type:'upload_receipt'},{type:'open_official_site'},{ownerConfirmed:false},{applicationId:'a2'},{programs:['medi_cal']},{sourceId:null}])test(`no inferred submission ${JSON.stringify(patch)}`,()=>assert.equal(recordSubmission('not_recorded',{...evt,...patch},'a1','calfresh'),'not_recorded'));
test('explicit report separate provenance',()=>assert.equal(recordSubmission('not_recorded',{...evt,type:'submission_report',provenance:'user_reported'},'a1','calfresh'),'user_reported'));
test('report does not downgrade receipt',()=>assert.equal(recordSubmission('receipt_recorded',{...evt,type:'submission_report',provenance:'user_reported'},'a1','calfresh'),'receipt_recorded'));
const job={workspaceId:'w',epoch:1,documentId:'d',documentRevision:1,cancelled:false};
test('current result accepted',()=>assert.equal(acceptJobResult(job,{...job}),true));
for(const patch of [{epoch:2},{documentRevision:2},{workspaceId:'w2'},{documentId:'d2'},{cancelled:true}])test(`stale job rejected ${JSON.stringify(patch)}`,()=>assert.equal(acceptJobResult(job,{...job,...patch}),false));
test('locked workspace rejects result',()=>assert.equal(acceptJobResult({...job,cancelled:true},job),false));

for(const patch of [{sourceIds:['']},{reviewerIds:['','engineer']},{jurisdiction:null}])test(`malformed policy blocked ${JSON.stringify(patch)}`,()=>assert.equal(policyMayRun({...pol,...patch},ctx),false));
test('missing jurisdiction on both sides never activates',()=>assert.equal(policyMayRun({...pol,jurisdiction:null},{...ctx,jurisdiction:null}),false));
test('missing confirmation map rejected',()=>assert.throws(()=>selectConfirmedFacts([f],{applicationId:'a1'},['f1'],'a1')));
test('null fact records do not bypass selection',()=>assert.throws(()=>selectConfirmedFacts([null],snap,['f1'],'a1')));
for(const patch of [{epoch:-1},{epoch:'1'},{documentRevision:0},{workspaceId:''}])test(`malformed job token rejected ${JSON.stringify(patch)}`,()=>assert.equal(acceptJobResult({...job,...patch},{...job,...patch}),false));
