import {PDFDocument} from '../vendor/pdf-writer/pdf-lib.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {renderOfficialForm,formPlan} from '../src/form-renderer.mjs';import {initial,manualFact,confirmFacts,setFact} from '../src/state.mjs';import {emptyAnswers,reviseGroup,reviseAnswer,confirmApplication,currentApplication,adoptFact} from '../src/form-adapter.mjs';import {evaluateStarting} from '../src/policy-engine.mjs';import * as Q from '../src/starting-state.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL('../forms/'+p,import.meta.url))),fontBytes=new Uint8Array(fs.readFileSync(new URL('../vendor/pdf-writer/NotoSans-Regular.ttf',import.meta.url)));
function payload(id='cf285',scenario='one-person'){const fixtureId=id+'-'+scenario,map=read('maps/'+id+'.json');return {template:new Uint8Array(fs.readFileSync(new URL('../forms/templates/'+id+'.pdf',import.meta.url))),inventory:read('inventory/'+id+'.json'),map,answers:read('fixtures/'+fixtureId+'.json'),fontBytes,mode:'developer',fixtureId,fixtureHash:map.developerFixtures[fixtureId]};}
for(const id of ['cf285','ccfrm604']){
 test(id+' release gate does not trust an unreviewed map',async()=>{const p=payload(id);assert.equal(formPlan(p.inventory,p.map,p.answers).canRender,false);await assert.rejects(renderOfficialForm({...p,mode:'released'}),/independent mapping review/);});
 test(id+' exact original renders locally with preserved page count and Unicode',async()=>{const p=payload(id),r=await renderOfficialForm(p);assert.equal(r.report.pageCount,id==='cf285'?18:44);assert(r.report.written.some(x=>x.text==='García'||x.text==='Jordan García'));assert.equal(r.report.signatureApplied,false);assert.equal(r.report.submitted,false);assert.equal(r.report.independentlyValidated,false);});
 test(id+' applicant draft writes confirmed values without claiming release approval',async()=>{const p=payload(id);p.mode='draft';p.answers.answers[0].value='Taylor Example';const r=await renderOfficialForm(p);assert.equal(r.report.mode,'draft');assert.equal(r.report.independentlyValidated,false);assert.equal(p.map.review.status,'draft');assert.equal(r.report.signatureApplied,false);assert.equal(r.report.submitted,false);const doc=await PDFDocument.load(r.bytes);const op=r.report.written.find(x=>x.text==='Taylor Example');assert(op);assert.equal(doc.getForm().getTextField(op.widget).getText(),'Taylor Example');});
 test(id+' draft requires confirmation and preserves template checks',async()=>{const p=payload(id);p.mode='draft';delete p.answers.answers[0].confirmedRevision;await assert.rejects(renderOfficialForm(p),/confirm all application answers/);const other=payload(id);other.mode='draft';other.template[20]^=1;await assert.rejects(renderOfficialForm(other),/SHA-256/);});
 test(id+' unknowns are missing, not No or zero',()=>{const p=payload(id),a=emptyAnswers(id),r=formPlan(p.inventory,p.map,a);assert.equal(r.operations.length,0);assert(r.missing.length>0);});
 test(id+' template alteration fails closed',async()=>{const p=payload(id);p.template[20]^=1;await assert.rejects(renderOfficialForm(p),/SHA-256/);});
 test(id+' edited fictional answer cannot use developer bypass',async()=>{const p=payload(id);p.answers.answers[0].value='Real person';await assert.rejects(renderOfficialForm(p),/registered fictional fixtures/);});
 test(id+' protected overlap and geometry mismatch fail closed',async()=>{const p=payload(id),b=p.map.bindings[0];p.map.protectedRegions.push({page:b.page,rect:b.rect,reason:'signature'});await assert.rejects(renderOfficialForm(p),/protected region/i);const p2=payload(id);p2.map.geometry[0].rotation=90;await assert.rejects(renderOfficialForm(p2),/geometry mismatch/);});
 test(id+' long text and row overflow remain explicit tasks',async()=>{const r=await renderOfficialForm(payload(id,'long-unicode'));assert(r.report.missing.some(m=>m.reason.includes('overflow')));const p=payload(id,'overflow'),plan=formPlan(p.inventory,p.map,p.answers);assert(plan.missing.some(m=>m.reason==='continuation_required_no_silent_truncation'));});
 test(id+' explicit No maps to only the actual No widget',()=>{const p=payload(id,'no-income'),r=formPlan(p.inventory,p.map,p.answers);const gate=r.operations.filter(x=>x.field===(id==='cf285'?'has_income':'household_has_income'));assert.equal(gate.length,1);assert.equal(gate[0].optionValue,false);assert.equal(gate[0].widget,id==='cf285'?'CF 285  270':'income_app-2');});
}
test('confirmed source adapter preserves person, period, and revisions; stale preview invalidated',()=>{const s=initial(),f=manualFact(s,{person:'Person A',period:'September',value:'1250'});confirmFacts(s);const a=emptyAnswers('cf285');assert.throws(()=>adoptFact(a,s,{groupId:'q8.earned',row:0,field:'gross_received_this_month'},f.id),/not a current confirmed answer/);reviseGroup(a,'q1.contact','applicable',1);reviseAnswer(a,{groupId:'q1.contact',row:0,field:'name',status:'answered',value:'Jordan'});const c=confirmApplication(a,s);assert(currentApplication(c,s));setFact(s,f,'1300');assert(!currentApplication(c,s));});
test('engine adapter keeps initial ranges separate from exact form answers',()=>{const s=initial();Q.setCalFresh(s.starting,'people','4');Q.setCalFresh(s.starting,'residence','yes');Q.setCalFresh(s.starting,'income','above');const r=evaluateStarting(s,'calfresh','2026-10-04');assert(r.evaluation.results[0].findings.some(f=>f.code==='above_mce_reference'));assert.deepEqual(s.formAnswers,{});Q.setCalFresh(s.starting,'income','at_or_below');assert(evaluateStarting(s,'calfresh','2026-10-04').evaluation.results[0].findings.some(f=>f.code==='within_mce_reference'));assert.equal(evaluateStarting(s,'medical','2026-10-04').input.facts.some(f=>f.key.includes('income')),false);});
