import test from 'node:test';import assert from 'node:assert/strict';
import {initial} from '../src/state.mjs';
import {qualificationHighlights,QUALIFICATION_SOURCES} from '../src/qualification.mjs';
test('household flags have sources and conditional applicability, not inferred findings',()=>{const s=initial();s.docs=[{kind:'medical',pages:[{text:'pregnancy disability'}]}];const flags=qualificationHighlights(s,'Household Details');assert.equal(flags.length,6);assert.ok(flags.every(f=>f.conditional&&QUALIFICATION_SOURCES[f.source]));assert.deepEqual(flags,qualificationHighlights(initial(),'Household Details'));assert.ok(!flags.some(f=>/tax|breastfeeding|immunization/i.test(f.input)));});
test('Medi-Cal selections and health answers do not establish CalFresh applicability',()=>{const s=initial();s.quick.special_group='yes';assert.ok(qualificationHighlights(s,'Household Details').every(f=>f.conditional));s.programs=new Set(['Medi-Cal']);assert.deepEqual(qualificationHighlights(s,'Household Details'),[]);});
test('expense amounts and missing proof alone do not create qualification warnings',()=>{const s=initial();s.facts=[{id:'rent',group:'Expenses',fieldKey:'rent_amount',value:null},{id:'care',group:'Household Details',fieldKey:'amount_billed',value:'200'}];assert.deepEqual(qualificationHighlights(s,'Expenses'),[]);assert.deepEqual(qualificationHighlights(s,'Income'),[]);});
test('income flags target unresolved live income, not stale or unrelated facts',()=>{const s=initial();s.facts=[{id:'gross',group:'Income',fieldKey:'gross_pay',value:null},{id:'old',group:'Income',fieldKey:'gross_pay',value:null,superseded:true},{id:'name',group:'Income',fieldKey:'person',value:null}];const flags=qualificationHighlights(s,'Income');assert.deepEqual(flags[0].affectedFactIds,['gross']);assert.equal(flags[0].conditional,false);});
test('starting range above guide never becomes a denial and within range never implies approval',()=>{const s=initial();s.quick.income='over';assert.match(qualificationHighlights(s,'Income')[0].action,/does not treat this range as a denial/);s.quick.income='within';assert.deepEqual(qualificationHighlights(s,'Income'),[]);});
test('known residency answer is reused instead of a repeat prompt',()=>{const s=initial();s.quick.resident='yes';assert.deepEqual(qualificationHighlights(s,'Your Information'),[]);s.quick.resident='unsure';assert.equal(qualificationHighlights(s,'Your Information').length,1);});
