import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
import * as M from '../src/starting-state.mjs';
const checks=[];
function test(name,fn){fn();checks.push({name,passed:true});}
let s;
test('All personal answers start blank',()=>{s=M.fresh();assert.equal(s.calfresh.residence,'');assert.equal(s.medical.people[0].age,'');assert.equal(s.medical.people[0].residence,'');});
test('Program statuses begin independently',()=>{assert.equal(M.status(s,'calfresh'),'Not started');assert.equal(M.status(s,'medical'),'Not started');});
test('No production reference activation',()=>assert.equal(M.CF_REFERENCE.productionEnabled,false));
test('Current four-person reference is 550000 cents',()=>assert.equal(M.threshold('4','2026-10-04'),550000));
for(const [n,c] of Object.entries({1:266000,2:360800,3:455400,4:550000,5:644800,6:739400,7:834000,8:928800}))test('Reference for '+n+' people',()=>assert.equal(M.threshold(n,'2026-10-04'),c));
test('First effective day included',()=>assert.equal(M.threshold('4','2026-10-01'),550000));
test('Last effective day included',()=>assert.equal(M.threshold('4','2027-09-30'),550000));
test('Reference unavailable before period',()=>assert.equal(M.threshold('4','2026-09-30'),null));
test('Reference unavailable after period',()=>assert.equal(M.threshold('4','2027-10-01'),null));
test('Unknown household not mapped to size one',()=>assert.equal(M.threshold('unknown','2026-10-04'),null));
test('Nine-plus not mapped to exact nine',()=>assert.equal(M.threshold('9plus','2026-10-04'),null));
test('No band can be chosen without reference',()=>assert.throws(()=>M.setCalFresh(s,'income','above','2026-10-04')));
test('CF self report does not fill MC residence',()=>{M.setCalFresh(s,'residence','yes');assert.equal(s.medical.people[0].residence,'');});
test('CF count does not create MC applicants',()=>{M.setCalFresh(s,'people','4');assert.equal(s.medical.people.length,1);});
test('CF band anchored to selected household reference',()=>{M.setCalFresh(s,'income','above','2026-10-04');assert.equal(s.calfresh.boundCents,550000);assert.equal(s.calfresh.referenceId,M.CF_REFERENCE.id);});
test('Save stores limited result and self-report only',()=>{const v=M.save(s,'calfresh','2026-10-04T10:00:00Z');assert.equal(v.eligibility,'not_assessed');assert.equal(v.verification,'not_performed');assert.equal(v.partial,false);});
test('CF save does not complete MC',()=>assert.equal(M.status(s,'medical'),'Not started'));
test('Above reference is not ineligibility',()=>{const r=M.overview(s,'calfresh','2026-10-04');assert.equal(r.comparison,'above_reference');assert.equal(r.eligibility,'not_assessed');});
test('Retained old snapshot is immutable after edit',()=>{const before=JSON.stringify(s.calfresh.saved);M.setCalFresh(s,'residence','unknown');assert.equal(JSON.stringify(s.calfresh.saved),before);assert.equal(M.status(s,'calfresh'),'Needs update');});
test('Unsaved changes suppress old comparison',()=>assert.equal(M.overview(s,'calfresh','2026-10-04').comparison,'needs_update'));
test('Changing household clears reference-based band',()=>{M.setCalFresh(s,'people','2');assert.equal(s.calfresh.income,'');assert.equal(s.calfresh.boundCents,null);});
test('At or below includes boundary category',()=>{M.setCalFresh(s,'income','at_or_below','2026-10-04');assert.equal(M.comparison(s.calfresh,'2026-10-04'),'at_or_below_reference');});
test('Stale reference suppresses display result',()=>assert.equal(M.comparison(s.calfresh,'2027-10-01'),'reference_expired'));
test('Corrupt anchor suppresses display result',()=>{const x={...s.calfresh,boundCents:1};assert.equal(M.comparison(x,'2026-10-04'),'reference_mismatch');});
test('No income remains explicit when household changes',()=>{M.setCalFresh(s,'income','none');M.setCalFresh(s,'people','3');assert.equal(s.calfresh.income,'none');assert.equal(M.comparison(s.calfresh),'no_income_reported');});
test('Blank is not no income',()=>assert.equal(M.comparison(M.fresh().calfresh),'not_compared'));
test('Unknown remains unknown',()=>{M.setCalFresh(s,'income','unknown');assert.equal(M.comparison(s.calfresh),'not_compared');});
test('Unknown residence remains unknown after save',()=>{M.save(s,'calfresh');assert.equal(s.calfresh.saved.facts.residence,'unknown');});
test('Invalid enum rejected',()=>assert.throws(()=>M.setCalFresh(s,'residence','qualified')));
test('Invalid program rejected',()=>assert.throws(()=>M.save(s,'other')));
test('Saving an empty form records partial, not successful check',()=>{const x=M.fresh();M.save(x,'calfresh');assert.equal(M.status(x,'calfresh'),'Partial answers saved');assert.equal(x.calfresh.saved.eligibility,'not_assessed');});
test('Skipping without answers does not manufacture snapshot',()=>{const x=M.fresh();M.skip(x,'medical');assert.equal(M.status(x,'medical'),'Skipped');assert.equal(x.medical.saved,null);});
test('Medi-Cal saves age and residence without money field',()=>{s=M.fresh();M.setMedical(s,'mc-person-1','age','19to64');M.setMedical(s,'mc-person-1','residence','yes');M.save(s,'medical');assert.deepEqual(Object.keys(s.medical.saved.facts),['people']);assert.equal(M.status(s,'medical'),'Answers saved');});
test('Adult age does not determine coverage category',()=>{assert.equal(M.overview(s,'medical').comparison,'not_compared');assert.equal(M.overview(s,'medical').eligibility,'not_assessed');});
test('MC changes do not invalidate CF saved facts',()=>{M.save(s,'calfresh');const old=JSON.stringify(s.calfresh.saved);M.setMedical(s,'mc-person-1','age','65plus');assert.equal(JSON.stringify(s.calfresh.saved),old);});
test('MC new person has independent blank residence',()=>{const id=M.addMedical(s);assert.equal(id,'mc-person-2');assert.equal(s.medical.people[1].residence,'');});
test('Mixed ages have distinct identifiers',()=>{M.setMedical(s,'mc-person-2','age','under19');assert.notEqual(s.medical.people[0].id,s.medical.people[1].id);});
test('Different residences not flattened to one household flag',()=>{M.setMedical(s,'mc-person-2','residence','no');assert.equal(s.medical.people[0].residence,'yes');assert.equal(s.medical.people[1].residence,'no');});
test('MC roster changes invalidate only its revision',()=>assert.equal(M.status(s,'medical'),'Needs update'));
test('Removing a person does not reuse old id',()=>{M.removeMedical(s,'mc-person-2');assert.equal(M.addMedical(s),'mc-person-3');});
test('Unknown person update rejected',()=>assert.throws(()=>M.setMedical(s,'missing','age','under19')));
test('No forced zero-person current form',()=>{const x=M.fresh();assert.equal(M.removeMedical(x,'mc-person-1'),false);});
test('Ten-person UI resource cap does not generate denial',()=>{const x=M.fresh();for(let i=0;i<9;i++)M.addMedical(x);assert.equal(M.addMedical(x),null);assert.equal(M.overview(x,'medical').eligibility,'not_assessed');});
test('Same value causes no spurious revision change',()=>{const x=M.fresh();M.setCalFresh(x,'residence','yes');const r=x.calfresh.revision;M.setCalFresh(x,'residence','yes');assert.equal(x.calfresh.revision,r);});
test('Saved result returned as independent copy',()=>{const x=M.fresh();const v=M.save(x,'medical');v.facts.people[0].age='under19';assert.equal(x.medical.saved.facts.people[0].age,'');});
console.log(checks.length+' integrated screen-model assertions passed');
