import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {initial,addDocument,manualFact,setFact,confirmFacts,usable,removeDocument,historical,recordEvent,submission,transferSnapshot,transferCurrent,gaps} from '../src/state.mjs';
const newDoc=(id='one',hash=id)=>({id,hash,filename:id+'.pdf',pages:[],fields:[],bytes:new Uint8Array([1]),analysisState:'complete'});
const result={kind:'paystub',fields:[{key:'person',value:'Test Person'},{key:'issuer',value:'Test Employer'},{key:'pay_date',value:'2026-09-15'},{key:'gross_pay',value:'1250.00'}],analysisState:'complete'};
test('exact duplicates are excluded; equal amounts in different files survive',()=>{const s=initial();addDocument(s,newDoc(),structuredClone(result));addDocument(s,newDoc('copy','one'),result);addDocument(s,newDoc('two'),result);assert.equal(s.docs[1].duplicateOf,'one');assert.equal(s.facts.filter(f=>f.fieldKey==='gross_pay').length,2);});
test('partial confirmation keeps unknowns unknown and freezes earlier snapshots',()=>{const s=initial();addDocument(s,newDoc(),{...result,fields:result.fields.filter(f=>f.key!=='gross_pay')});const snap=confirmFacts(s),f=s.facts.find(f=>f.fieldKey==='gross_pay');assert.equal(f.value,null);assert.equal(usable(f),false);assert.equal(snap.unresolved.length,1);setFact(s,f,'0');assert.equal(usable(f),false);confirmFacts(s);assert.ok(usable(f));assert.equal(snap.facts.length,3);assert.equal(gaps(s).length,0);});
test('changing one fact preserves other confirmations and invalidates transfers',()=>{const s=initial();addDocument(s,newDoc(),structuredClone(result));confirmFacts(s);const before=transferSnapshot(s),f=s.facts.find(f=>f.fieldKey==='gross_pay');setFact(s,f,'1400');assert.equal(usable(f),false);assert.ok(usable(s.facts[0]));assert.equal(transferCurrent(s,before),false);assert.equal(s.snapshots[0].facts.find(f=>f.fieldKey==='gross_pay').value,'1250.00');});
test('manual zero is explicit; blank does not become zero',()=>{const s=initial();assert.throws(()=>manualFact(s,{person:'Test',period:'September',value:''}));const f=manualFact(s,{person:'Test',period:'September',value:'0'});assert.equal(f.value,'0.00');assert.equal(gaps(s)[0].label,'Can add later');});
test('moving history or deleting source removes active answers without mutating snapshots',()=>{const s=initial();addDocument(s,newDoc(),structuredClone(result));confirmFacts(s);historical(s,'one');assert.equal(s.facts.filter(usable).length,0);historical(s,'one');assert.equal(s.facts.filter(usable).length,0);removeDocument(s,'one');assert.equal(s.facts.length,0);assert.equal(s.snapshots[0].facts.length,4);});
test('events require provenance and isolate program and upload status',()=>{const s=initial();assert.throws(()=>recordEvent(s,{kind:'application_receipt',program:'CalFresh',details:'Submitted'}));s.docs.push(newDoc('receipt'));const request=recordEvent(s,{kind:'evidence_request',program:'CalFresh',sourceId:'receipt',details:'September pay',deadline:'2026-10-16'});recordEvent(s,{kind:'upload_receipt',program:'CalFresh',sourceId:'receipt',details:'Sent file',requestId:request.id});assert.equal(submission(s),'Submission not recorded');assert.throws(()=>recordEvent(s,{kind:'upload_receipt',program:'Medi-Cal',sourceId:'receipt',details:'Wrong track',requestId:request.id}));recordEvent(s,{kind:'application_receipt',program:'CalFresh',sourceId:'receipt',details:'Submitted'});assert.equal(submission(s),'Submitted — receipt recorded');assert.equal(submission(s,'Medi-Cal'),'Submission not recorded');});
test('invalid dates rejected; reports and source receipts remain distinct',()=>{const s=initial();assert.throws(()=>recordEvent(s,{kind:'user_reported_submission',program:'CalFresh',details:'Submitted',date:'2026-02-30'}));recordEvent(s,{kind:'user_reported_submission',program:'CalFresh',details:'Submitted'});assert.equal(submission(s),'Submitted — reported by you');});

test('extension is separate, no host/content-script/storage permissions',()=>{const manifest=JSON.parse(fs.readFileSync(new URL('../extension/manifest.json',import.meta.url)));assert.deepEqual(manifest.permissions,['sidePanel']);assert.equal(manifest.host_permissions,undefined);assert.equal(manifest.content_scripts,undefined);assert.ok(manifest.content_security_policy.extension_pages.includes("script-src 'self'"));});
test('support received is income; paid is expense; unknown direction remains other',()=>{for(const [direction,group]of [['received','Income'],['paid','Expenses'],['unknown','Other Situations']]){const s=initial();addDocument(s,newDoc(),{kind:'support',fields:[{key:'support_direction',value:direction},{key:'amount_paid',value:'350.00'}]});assert.equal(s.facts[0].group,group);}});
test('person corrections invalidate dependent attribution without rewriting history',()=>{const s=initial();addDocument(s,newDoc(),structuredClone(result));confirmFacts(s);setFact(s,s.facts.find(f=>f.fieldKey==='person'),'Correct Person');assert.ok(s.facts.every(f=>f.person==='Correct Person'));assert.ok(s.facts.every(f=>!usable(f)));assert.equal(s.snapshots[0].facts[0].person,'Test Person');});

 test('four questions and income ranges replace exact amount input',async()=>{const {quickView}=await import('../src/quick.mjs');const s=initial();s.quick.food='2';const html=quickView({head:()=>'',state:s,icon:()=>'',selectedOption:(a,b)=>a===b?' selected':'',esc:String});assert.equal((html.match(/data-screen-question=/g)||[]).length,4);assert.match(html,/\$3,608/);assert.match(html,/Could one applicant meet immigration rules/);assert.doesNotMatch(html,/type="number"/);s.quickProgram='medi_cal';const medical=quickView({head:()=>'',state:s,icon:()=>'',selectedOption:()=>'',esc:String});assert.equal((medical.match(/data-screen-question=/g)||[]).length,4);assert.match(medical,/special health eligibility/);});
