// Matches are navigation aids, never verification or eligibility decisions.
export const MEDI_CAL_GROUPS = [
 {id:'identity',title:'Identity of applicant',examples:'Birth certificate, driver’s license, passport, school or government ID, paycheck, award letter, or Medicare card.',kinds:['paystub'],pattern:/\b(birth certificate|driver.?s license|passport|school record|military id|tribal document|medicare card)\b/i,note:'Check whose document this is. A match does not verify identity. Enter sensitive identifiers directly in the application when requested.'},
 {id:'immigration',title:'Immigration documents, if requested',examples:'Immigration cards or papers, naturalization certificate, work authorization, or USCIS correspondence. Include both sides when requested.',kinds:[],pattern:/\b(uscis|naturalization|employment authorization|permanent resident card)\b/i,note:'Use the application’s questions for each applicant. We do not infer immigration status or coverage eligibility from a document.'},
 {id:'residency',title:'Proof you live in California',examples:'Rent or mortgage receipt, utility bill, check stub, school record, or government document showing a California address.',kinds:['rent','mortgage','utility','paystub'],pattern:/\b(driver.?s license|school record)\b/i,note:'Open the original and check the person and California address. Document type alone does not establish residency.'},
 {id:'earned',title:'Money you earn',examples:'Recent dated pay stubs, employer statement, tax return, or bank statement showing direct deposit.',kinds:['paystub'],pattern:/\b(tax return|employer statement|direct deposit)\b/i,note:'Check the requested date range and whose income it is. Individual pay amounts are not automatically expected monthly income.'},
 {id:'other',title:'Other income',examples:'Benefit or award letters, benefit payments, child support received, or alimony received.',kinds:['support'],pattern:/\b(award letter|benefit payment|alimony)\b/i,note:'Check whether support is received or paid. A support payment is not automatically household income.'},
 {id:'resources',title:'Resources — only when applicable',examples:'Bank, investment, life insurance, trust, mortgage, or vehicle records requested for your Medi-Cal pathway.',kinds:['mortgage'],pattern:/\b(bank statement|savings account|checking account|life insurance|stock|certificate of deposit|trust document|vehicle registration)\b/i,note:'Asset rules apply to some Medi-Cal pathways. Follow the actual application or county request; this is not a required checklist for everyone.'},
 {id:'coverage',title:'Current or offered health coverage',examples:'Current insurance information and information about job-related coverage available to your family.',kinds:[],pattern:/\b(health insurance|health plan|insurance policy|summary of benefits|employer coverage)\b/i,note:'A medical bill or insurer payment does not establish current coverage. Check policy information and whether employer coverage is available.'},
 {id:'bills',title:'Medical bills, if requested',examples:'Medical bills relevant to your application or a county request.',kinds:['medical'],pattern:null,note:'A bill does not establish disability or a diagnosis. Keep medical details in the original document.'}
];
export function mediCalMatches(documents){return MEDI_CAL_GROUPS.map(group=>({...group,matches:documents.filter(d=>!d.duplicateOf&&(!d.possibleDuplicateOf||d.duplicateResolved)).filter(d=>group.kinds.includes(d.kind)||group.pattern?.test((d.pages||[]).map(p=>p.text||'').join('\n'))).map(d=>({id:d.id,filename:d.filename,reviewed:!!d.reviewed,facts:d.reviewed?(d.fields||[]).filter(f=>f.confirmed&&!f.conflict&&['person','issuer','pay_date','gross_pay','pay_frequency','support_direction','amount_paid','patient_responsibility'].includes(f.key)):[]}))}));}
