"""Generate a candid data/model report from frozen results. Never fits a model."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
m=json.loads((ROOT/'artifacts/metrics.json').read_text());audit=json.loads((ROOT/'artifacts/data-audit.json').read_text());browser=json.loads((ROOT/'artifacts/browser-check.json').read_text());manifest=json.loads((ROOT/'data/manifest.json').read_text())
report=['# More realistic document training — v0.2 candidate','',
'Created 144 fictional documents across 36 authored scenario families, with a searchable PDF and a degraded scan of each: **288 paired text examples**. PDF text comes from the app’s PDF.js reader; scan text comes from actual local Apple Vision OCR. There is no hidden answer layer, scripted OCR corruption or gold-label injection into inference.','',
'**This candidate is not ready to replace the shipped classifier.** It failed the predeclared validation precision/coverage gate. The new synthetic test produced 14 correct suggestions, 34 unknowns and no wrong accepted suggestions at threshold 0.70. All 16 pay-record captures were unknown. Before abstention, it misclassified all 16 “other” captures (pay simulations and insurance explanations). This is a useful training corpus and a measured failure, not evidence of production readiness.','',
'## Inspect the documents','',
'Open [the visual gallery](data/realistic-v1/index.html). It shows one of four variants from each family and links to the PDF, scan, extracted PDF text and actual OCR text. All people, organizations, identifiers and transactions are fictional. The screenshots supplied in the conversation were examples of structure; their pixels, personal details and text were not incorporated.','',
'Examples include hourly and salaried wage statements, check/stub copies, payroll portal records, tips and commissions, utilities with old balances, rent receipts, childcare and medical bills, payroll-service invoices, bank deposits, leases, employment offers, tax summaries, coverage information, verification requests, pay projections and insurance explanations. These are **36 authored scenarios, not 36 trained output classes**. The classifier still has three broad outputs: pay statement, invoice/receipt and other document, plus abstention as unknown.','',
'## Dataset sizes','',
'| Partition | Public documents retained | New synthetic documents | New paired captures | Total model rows | Unique documents |',
'|---|---:|---:|---:|---:|---:|']
for s,public,new in [('train',460,96),('validation',144,24),('test',0,24),('regression',163,0)]:
 c=m['counts'][s];report.append(f"| {s} | {public} | {new} | {new*2} | {c['rows']} | {c['unique_documents']} |")
report+=['',
'The 460 public training records are the original 285 PAYSLIPS records, 155 selected synthetic FieldBench records and 20 CORD receipts. No new public records were downloaded in this experiment. The original public validation split is retained. The 163 previously examined public test documents are a regression check only; they are not a fresh holdout. Public attribution and licences remain in [the existing source manifest](../document_classifier/data/source_manifest.json) and [model notices](../../models/NOTICE.md).','',
'The new corpus assigns 24 authored families to training, six to validation and six to test before fitting. Each family has four document variations. Both captures of a document stay together. Training, validation and test also use separate layout-theme pools. Exact normalized text duplicates across partitions are rejected. Common tables, vocabulary, fictional identity pools and rendering components remain shared: this is **not an independent real-issuer/template test**, and synthetic scores can be optimistic. Existing challenge and video packs were not used for fitting or as a new test.','',
'## Frozen evaluation','',
'| New test: 48 captures of 24 documents | Shipped v0.1 baseline | v0.2 candidate |',
'|---|---:|---:|']
for label,key in [('Correct accepted suggestions','accepted'),('Unknown','abstained'),('Wrong accepted suggestions','confident_errors')]:
 b=m['test']['baseline_v0_1'];c=m['test']['candidate'];bv=b[key];cv=c[key]
 if key=='accepted':bv-=b['confident_errors'];cv-=c['confident_errors']
 report.append(f'| {label} | {bv} | {cv} |')
report+=['| Raw top-class accuracy before abstention | 32/48 (66.7%) | 32/48 (66.7%) |','',
'Candidate: six of 24 original documents had both captures correctly suggested; 18 had at least one unknown. The 14 accepted captures were invoices/receipts. No pay-record capture was accepted. A projection or explanation being unknown does not mean the classifier correctly understood its purpose. Scores are uncalibrated, so 0.70 is a decision threshold, not “70% confident it is right.”','',
'The inherited public regression test had 77 correct accepted suggestions and 86 unknowns. Its raw top-class result was 162/163. That narrower, previously inspected result does not supersede the new synthetic-test failure.','',
'## Model and measured speed','',
f"The architecture remains 8,192 hashed word/bigram TF-IDF features with multinomial logistic regression. IDF and weights use training rows only. Paired synthetic captures receive half weight each. C={m['selection'][0]['C']} was selected by mean public/synthetic validation macro-F1 (lower C breaks ties). Threshold selection required at least 95% accepted precision and 50% coverage in both validation domains; no candidate threshold passed, so the reported fallback threshold does not authorize release.", '',
f"Chrome {browser['browser'].split('/')[-1]} on local macOS/arm64 classified 48 already-extracted texts in a median **{browser['medianBatchMilliseconds']:.1f} ms** across ten warm batches. This excludes model loading, PDF reading, OCR, field extraction and UI. All 48 browser predictions match the frozen Python results. Local training OCR took a median **{audit['trainingOCRLatencyMs']['median']:.0f} ms/image**; this is a separate macOS tool, not an OCR capability added to the extension.", '',
'## Files and reproduction','',
'- `corpus.py`: authored content, fictional values and declared family/theme partitions.\n- `build_corpus.py`: Chrome rendering, one-page/overflow checks, real PDF.js reading and scan construction.\n- `ocr.swift`: local macOS Vision OCR; bounding boxes and recognition confidence are saved separately.\n- `data/generation_plan.json`, `data/manifest.json`: frozen generation policy, family labels and PDF/scan hashes.\n- `data/synthetic_records.jsonl`: 288 labeled text rows with parent document, family, capture and split.\n- `data/split_manifest.json`: combined public/synthetic split membership.\n- `train.py`: fits the candidate and selects settings on validation; refuses to overwrite a frozen candidate.\n- `artifacts/model.json`, `metrics.json`, `predictions.json`: weights, complete metrics and individual outcomes.\n- `audit.py`, `verify.mjs`, `browser_check.py`: hash/split integrity and Python/JavaScript/Chrome parity.','',
'From the repository root, a new unevaluated copy can render with `python3 BenefitStep_v0_1/ml/document_classifier_v0_2/build_corpus.py` and train using `BenefitStep_v0_1/ml/document_classifier/.venv/bin/python BenefitStep_v0_1/ml/document_classifier_v0_2/train.py`. Rendering requires local Chrome and macOS Command Line Tools/Vision; model training uses the existing pinned requirements in v0.1. Public caches and their original splits must be present. Do not regenerate or refit this evaluated version to tune against its test.','',
'Existing artifacts can be checked without retraining:','',
'```sh\npython3 BenefitStep_v0_1/ml/document_classifier_v0_2/audit.py\nnode BenefitStep_v0_1/ml/document_classifier_v0_2/verify.mjs\npython3 BenefitStep_v0_1/ml/document_classifier_v0_2/browser_check.py\n```','',
'## What remains','',
'The synthetic corpus broadens training conditions but does not supply new real-world validation. The next model experiment needs stronger semantic discrimination and more independently sourced, permissioned document families, especially bill-versus-explanation and paid-wages-versus-projection pairs. A new untouched evaluation set is required after making those changes. General browser OCR, detailed benefit-document categorization, field extraction and Package Doctor are separate work. The extension continues to ship v0.1; this candidate has not replaced it.','']
(ROOT/'README.md').write_text('\n'.join(report))
register={'dataset':'benefitstep-realistic-synthetic-v1','experiment':'realistic-text-v0.2','candidateModelId':'benefitstep-realistic-text-candidate-v0.2','modelSha256':m['modelSha256'],'documents':144,'authoredFamilies':36,'pairedCaptureRows':288,'counts':m['counts'],'newDataIsSynthetic':True,'userDocumentsUsed':False,'newPublicDocumentsDownloaded':0,'modelOutputs':['pay_statement','invoice_or_receipt','other_document'],'fineGrainedTypesTrained':False,'validationGatePassed':m['validation']['gate'],'productionRoutingApproved':False,'deployedToExtension':False,'dataManifest':'data/manifest.json','report':'README.md'}
(ROOT/'dataset_register.json').write_text(json.dumps(register,indent=2)+'\n')
root_register=ROOT.parent/'dataset_register.json';r=json.loads(root_register.read_text());r['latestCandidate']={'modelId':register['candidateModelId'],'register':'document_classifier_v0_2/dataset_register.json','report':'document_classifier_v0_2/README.md','deployed':False,'validationGatePassed':False};root_register.write_text(json.dumps(r,indent=2)+'\n')
print('Wrote README.md and versioned dataset register; shipped model unchanged.')
